# Generated by Django 5.0.3 on 2024-03-23 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paint',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Amount in liters'),
        ),
        migrations.AlterField(
            model_name='paint',
            name='colour',
            field=models.CharField(max_length=100, verbose_name="Colour in hex format, ie. '#a1a1a1'"),
        ),
    ]
