# Generated by Django 5.0.3 on 2024-03-23 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_paint_amount_alter_paint_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='paint',
            name='text_colour',
            field=models.CharField(default='#000000', max_length=100, verbose_name="Colour in hex format, ie. '#a1a1a1'"),
            preserve_default=False,
        ),
    ]
